import socket
import os
import sys
os.system ("clear")
print ('\33[1;31m')
print ('                R̷i̷O̷  A̷l̷g̷e̷r̷i̷a̷n̷              ')
print ('\33[1;35m')
print ('===================RiO===================')
print ('========= RiO Anonymous Algeria =========')
print ('≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠ Welcom ≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠')
print ('                                         ')
print ('\33[1;31m')
print ('                    °   °                ')
print ('                   ° ° °                 ')
print ('                  °   °                  ')
print ('                 °   ° °                 ')
print ('                °   °   °                ')
print ('               °   °     °               ')
print ('              °   °       °              ')
print ('             °   °         °             ')
print ('            °   °           °            ')
print ('           °   °             °           ')
print ('          °   °               °          ')
print ('         °   °                 °         ')
print ('        °   °                   °        ')
print ('       °   °                     °       ')
print ('      °   °                       °      ')
print ('     °   °                         °     ')
print ('    °   °                           °    ')
print ('   °   °                             °   ')
print ('  °   °                               °  ')
print (' °   °                                 ° ')
print ('°   °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°')
print ('\33[1;33m')
print ('       RiO The programmer of Algeria ')
print (' ')
print ('           Welcome to RiO script')
print ('\33[1;35m')
print (' Please enter the site link : ')
print (' -------------------------- ')
hostname  = input ()
ip = socket.gethostbyname(hostname)
print ('the site link Is: ',hostname,)
print ('link IP Is : ',ip) 